#!/usr/bin/env bash
#
# Phase 5 CI guard — fail the build if any Grid-shaped symbol slips back in.
#
# The KYC migration to Sumsub is a separate swarm scheduled LAST; until that
# swarm runs, KYC keeps working through the existing Grid + Bridge stack via
# a curated allowlist of files. The allowlist below names every file that
# may still legitimately reference Grid for KYC. When the KYC swarm replaces
# Grid with Sumsub, delete the allowlist and re-run this script.
#
# Forbidden patterns are searched across all source/text formats under
# apps/, excluding node_modules and dist.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Forbidden patterns. Each entry is an ERE regex passed to grep -E.
# `@sqds/grid([^-]|$)` matches `@sqds/grid` and `@sqds/grid"` etc. but NOT
# `@sqds/grid-react-native` (KYC carve-out — kept alive on mobile).
FORBIDDEN_PATTERNS=(
  '@sqds/grid([^-]|$)'
  'GRID_API_KEY'
  'EXPO_PUBLIC_GRID_ENDPOINT'
  'EXPO_PUBLIC_GRID_ENV'
  'EXPO_PUBLIC_USE_NEW_STACK'
  'EXPO_PUBLIC_API_ENDPOINT'
  '@hpke/'
  '@noble/curves'
  '@stablelib/'
  '@ethersproject'
  "from ['\"]ethers['\"]"
  'passkey-callback'
  'smartAccount\.ts'
  # No provider RPC URL with a hardcoded api-key literal may live in source —
  # it would ship in the device bundle (or leak the key in the repo). Matches
  # a real key value (hex/UUID-shaped, 12+ chars) after `api-key=`, so the
  # backend adapter (which reads the key from env) and test fixtures using a
  # `test` placeholder are not flagged. Adapters read the key from env.
  'helius-rpc\.com/\?api-key=[0-9a-fA-F-]{12,}'
)

# KYC carve-out — these paths may legitimately reference Grid until the
# Sumsub swarm runs. ERE; the parens around (modals) are escaped.
KYC_ALLOWLIST_REGEX='(apps/mobile/app/api/kyc\+api\.ts|apps/mobile/app/api/kyc-status\+api\.ts|apps/mobile/grid/sdkClient\.ts|apps/mobile/utils/easClient\.ts|apps/mobile/utils/mockDatabase\.ts|apps/mobile/hooks/useKyc\.ts|apps/mobile/app/\(modals\)/kyc\.tsx|apps/mobile/app/\(modals\)/bankdetails\.tsx|apps/mobile/types/Kyc\.ts|apps/mobile/example\.env|apps/mobile/package\.json|apps/mobile/package-lock\.json|apps/mobile/contexts/AuthContext\.tsx|apps/mobile/types/Auth\.ts|apps/mobile/app/_layout\.tsx|apps/backend/src/config/config\.module\.ts)'

failed=0

for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
  # Skip gitignored artefacts: per-user .env files (not part of repo
  # state — operators control their own), .expo/ generated types, ios/
  # and android/ native projects (regenerated by `expo prebuild`), and
  # node_modules / dist build outputs.
  hits="$(grep -rE "$pattern" apps/ \
    --include='*.ts' --include='*.tsx' --include='*.js' \
    --include='*.json' --include='example.env' \
    --exclude-dir=node_modules --exclude-dir=dist \
    --exclude-dir=ios --exclude-dir=android \
    --exclude-dir=.expo \
    --exclude='*.env' --exclude='.env*' \
    || true)"

  if [ -z "$hits" ]; then
    continue
  fi

  # Strip the allowlisted paths; if any non-allowlisted hits remain, fail.
  remaining="$(echo "$hits" | grep -vE "$KYC_ALLOWLIST_REGEX" || true)"

  if [ -n "$remaining" ]; then
    echo "Forbidden pattern found: $pattern"
    echo "$remaining"
    failed=1
  fi
done

if [ "$failed" -ne 0 ]; then
  echo
  echo "scripts/check-no-grid.sh: forbidden patterns detected outside the KYC allowlist."
  echo "If a legitimate KYC use site triggered this, add it to KYC_ALLOWLIST_REGEX."
  echo "Otherwise rip the Grid reference out — Phase 5 removed Grid from every"
  echo "non-KYC path."
  exit 1
fi

echo "check-no-grid: PASS — no forbidden patterns outside the KYC allowlist."
